OPENAI_API_KEY = "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"
PINECONE_API_KEY = "7945ccd6-81af-4de2-a379-7ee680d944a7"
PINECONE_ENVIRONMENT = "asia-northeast1-gcp"
LANGCHAIN_TRACING_V2= true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="ls__8a009e9110274778bb99d438d13f3d5c"
